default:
  image: python:3.8-slim

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - deploy

test:
  stage: test

  services:
    - postgres:13

  variables:
    POSTGRES_DB: "accounting"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "marmot"

  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - sh test-start.sh

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

  artifacts:
    reports:
      cobertura: coverage.xml

release:
  stage: deploy
  needs: [test]
  image: docker:19.03

  services:
    - docker:dind

  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    POSTGRES_HOST_AUTH_METHOD: trust

  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build
        --cache-from $CONTAINER_IMAGE:latest
        --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA
        --tag $CONTAINER_IMAGE:latest
        --build-arg BUILDKIT_INLINE_CACHE=1
        "."
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest
  only:
    - main
