"""Add forebay

Revision ID: 09139eb84a48
Revises: 3f4d0ee68a0e
Create Date: 2022-08-06 11:43:56.080073

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "09139eb84a48"
down_revision = "3f4d0ee68a0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_data", sa.Column("forebay_capacity", sa.Float(), nullable=True)
    )
    op.add_column(
        "project_data", sa.Column("forebay_length", sa.Float(), nullable=True)
    )
    op.add_column("project_data", sa.Column("forebay_width", sa.Float(), nullable=True))
    op.add_column("project_data", sa.Column("forebay_depth", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_data", "forebay_depth")
    op.drop_column("project_data", "forebay_width")
    op.drop_column("project_data", "forebay_length")
    op.drop_column("project_data", "forebay_capacity")
    # ### end Alembic commands ###
