"""Add legal consents for schedule

Revision ID: 0b1df31e9bdc
Revises: d250e4056568
Create Date: 2022-08-06 12:12:29.191397

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0b1df31e9bdc"
down_revision = "d250e4056568"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "power_schedule", sa.Column("legal_consents", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power_schedule", "legal_consents")
    # ### end Alembic commands ###
