"""Add tech type

Revision ID: 0daa8983e17b
Revises: 77002e0c9436
Create Date: 2022-05-18 21:27:01.666125

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0daa8983e17b"
down_revision = "77002e0c9436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "technology_type",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("technology_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["technology_id"], ["technology.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("power_hydropower_type_id_fkey", "power", type_="foreignkey")
    op.drop_table("hydropower_type")
    op.add_column("power", sa.Column("sponsor_name", sa.Text(), nullable=True))
    op.add_column(
        "power",
        sa.Column("technology_type_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        None,
        "power",
        "technology_type",
        ["technology_type_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("power", "hydropower_type_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "power",
        sa.Column(
            "hydropower_type_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "power", type_="foreignkey")
    op.create_foreign_key(
        "power_hydropower_type_id_fkey",
        "power",
        "hydropower_type",
        ["hydropower_type_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("power", "technology_type_id")
    op.drop_column("power", "sponsor_name")
    op.create_table(
        "hydropower_type",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="hydropower_type_pkey"),
    )
    op.drop_table("technology_type")
    # ### end Alembic commands ###
