"""Add project debt description

Revision ID: 0f391f7d32df
Revises: 97d5fd1c96de
Create Date: 2022-07-24 20:09:28.122455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f391f7d32df'
down_revision = '97d5fd1c96de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_investment', sa.Column('debt_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_investment', 'debt_description')
    # ### end Alembic commands ###
