"""Add project team bool

Revision ID: 10082d29a844
Revises: 74e60212e914
Create Date: 2022-08-07 14:28:41.722229

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "10082d29a844"
down_revision = "74e60212e914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_team",
        sa.Column(
            "has_team", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_team", "has_team")
    # ### end Alembic commands ###
