"""Change capacity to string

Revision ID: 16d08ba7299c
Revises: 96cd5a1602da
Create Date: 2022-07-25 21:17:10.846592

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "16d08ba7299c"
down_revision = "96cd5a1602da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE power DROP CONSTRAINT power_capacity_id_fkey")
    op.execute(
        "ALTER TABLE project_data DROP CONSTRAINT project_data_turbine_capacity_id_fkey"
    )
    op.alter_column(
        "capacity",
        "id",
        existing_type=postgresql.UUID(),
        type_=sa.Text(),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.alter_column(
        "power",
        "capacity_id",
        existing_type=postgresql.UUID(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "project_data",
        "turbine_capacity_id",
        existing_type=postgresql.UUID(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_data",
        "turbine_capacity_id",
        existing_type=sa.Text(),
        type_=postgresql.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "power",
        "capacity_id",
        existing_type=sa.Text(),
        type_=postgresql.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "capacity",
        "id",
        existing_type=sa.Text(),
        type_=postgresql.UUID(),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    # ### end Alembic commands ###
