"""Can have multiple documents of a type

Revision ID: 1716baffb359
Revises: 891f79839657
Create Date: 2022-06-06 15:58:12.965994

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1716baffb359"
down_revision = "891f79839657"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("project_document_unique", table_name="project_document")
    op.create_index(
        "project_document_unique",
        "project_document",
        ["project_id", "name", "document_type"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("project_document_unique", table_name="project_document")
    op.create_index(
        "project_document_unique",
        "project_document",
        ["project_id", "document_type"],
        unique=False,
    )
    # ### end Alembic commands ###
