"""Use arrays to hold list of texts

Revision ID: 1ecb89107214
Revises: 7c3672c3642e
Create Date: 2022-07-22 11:59:08.839764

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1ecb89107214"
down_revision = "7c3672c3642e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE project ALTER COLUMN other_countries TYPE text[] using other_countries::text[]"
    )
    op.execute(
        "ALTER TABLE power ALTER COLUMN other_resources TYPE text[] using other_resources::text[]"
    )
    op.execute(
        "ALTER TABLE power ALTER COLUMN other_technologies TYPE text[] using other_technologies::text[]"
    )
    op.execute(
        "ALTER TABLE power ALTER COLUMN other_service_ids TYPE text[] using other_service_ids::text[]"
    )
    op.execute(
        "ALTER TABLE power ALTER COLUMN other_customer_ids TYPE text[] using other_customer_ids::text[]"
    )
    op.execute(
        "ALTER TABLE sponsor ALTER COLUMN other_countries TYPE text[] using other_countries::text[]"
    )
    op.execute(
        "ALTER TABLE sponsor ALTER COLUMN other_sectors TYPE text[] using other_sectors::text[]"
    )
    op.execute(
        "ALTER TABLE sponsor ALTER COLUMN sponsor_types TYPE text[] using sponsor_types::text[]"
    )
    op.execute(
        "ALTER TABLE project_investment ALTER COLUMN other_loan_types TYPE text[] using other_loan_types::text[]"
    )
    op.execute(
        "ALTER TABLE power_product ALTER COLUMN other_services TYPE text[] using other_services::text[]"
    )
    op.execute(
        "ALTER TABLE power_product ALTER COLUMN other_customers TYPE text[] using other_customers::text[]"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
