"""Add dev status

Revision ID: 22d9e24ef69a
Revises: 1ecb89107214
Create Date: 2022-07-23 16:57:13.962971

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "22d9e24ef69a"
down_revision = "1ecb89107214"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("development_status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "development_status")
    # ### end Alembic commands ###
