"""Change sponsor type field

Revision ID: 32d4f8b49a67
Revises: 566ea3fea8dd
Create Date: 2022-05-31 23:22:40.308054

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "32d4f8b49a67"
down_revision = "566ea3fea8dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor", sa.Column("sponsor_types", sa.Text(), nullable=True))
    op.drop_constraint("sponsor_sponsor_type_id_fkey", "sponsor", type_="foreignkey")
    op.drop_column("sponsor", "sponsor_type_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sponsor",
        sa.Column(
            "sponsor_type_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "sponsor_sponsor_type_id_fkey",
        "sponsor",
        "sponsor_type",
        ["sponsor_type_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.drop_column("sponsor", "sponsor_types")
    # ### end Alembic commands ###
