"""Add partners

Revision ID: 41b4a3c1487e
Revises: 78db9eab37e2
Create Date: 2022-05-20 06:58:35.589795

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "41b4a3c1487e"
down_revision = "78db9eab37e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_partner",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("equity_partners", sa.Text(), nullable=True),
        sa.Column("debt_partners", sa.Text(), nullable=True),
        sa.Column("tehcnical_advisors", sa.Text(), nullable=True),
        sa.Column("implementation_partners", sa.Text(), nullable=True),
        sa.Column("institutional_partners", sa.Text(), nullable=True),
        sa.Column("stakeholders", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_partner")
    # ### end Alembic commands ###
