"""Add other-resources

Revision ID: 4f8cc396d56e
Revises: fae45380e6e6
Create Date: 2022-06-21 20:35:50.566400

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f8cc396d56e"
down_revision = "fae45380e6e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("other_resources", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "other_resources")
    # ### end Alembic commands ###
