"""Add northings for intake

Revision ID: 5059e9cd3773
Revises: 906edd47c0fd
Create Date: 2022-07-04 10:57:18.221706

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5059e9cd3773"
down_revision = "906edd47c0fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("northings_intake", sa.Text(), nullable=True))
    op.add_column("power", sa.Column("eastings_intake", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "eastings_intake")
    op.drop_column("power", "northings_intake")
    # ### end Alembic commands ###
