"""Add project owner

Revision ID: 5554d4bf0dd2
Revises: 1716baffb359
Create Date: 2022-06-09 13:53:35.767741

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5554d4bf0dd2"
down_revision = "1716baffb359"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "account_id")
    # ### end Alembic commands ###
