"""More sponsor fields

Revision ID: 566ea3fea8dd
Revises: 7df2395a0799
Create Date: 2022-05-31 23:06:31.924191

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "566ea3fea8dd"
down_revision = "7df2395a0799"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor", sa.Column("countries", sa.Text(), nullable=True))
    op.add_column("sponsor", sa.Column("sector_industry_id", sa.Text(), nullable=True))
    op.add_column("sponsor", sa.Column("other_sectors", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsor", "other_sectors")
    op.drop_column("sponsor", "sector_industry_id")
    op.drop_column("sponsor", "countries")
    # ### end Alembic commands ###
