"""Add planning schedule


Revision ID: 5de0541ea584
Revises: 26f0b46bd8ad
Create Date: 2022-07-21 18:45:43.259973

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5de0541ea584"
down_revision = "26f0b46bd8ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "power_schedule", sa.Column("planning_schedule", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power_schedule", "planning_schedule")
    # ### end Alembic commands ###
