"""Split title and source

Revision ID: 62a3c25893a9
Revises: ed5eb43b2dab
Create Date: 2022-07-26 10:42:13.203629

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "62a3c25893a9"
down_revision = "ed5eb43b2dab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("picture_title", sa.Text(), nullable=True))
    op.drop_constraint("power_capacity_id_fkey", "power", type_="foreignkey")
    op.create_foreign_key(
        op.f("power_capacity_id_fkey"),
        "power",
        "capacity",
        ["capacity_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "project_data_turbine_capacity_id_fkey", "project_data", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("project_data_turbine_capacity_id_fkey"),
        "project_data",
        "capacity",
        ["turbine_capacity_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.add_column("project_document", sa.Column("source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_document", "source")
    op.drop_constraint(
        op.f("project_data_turbine_capacity_id_fkey"),
        "project_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "project_data_turbine_capacity_id_fkey",
        "project_data",
        "capacity",
        ["turbine_capacity_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("power_capacity_id_fkey"), "power", type_="foreignkey")
    op.create_foreign_key(
        "power_capacity_id_fkey",
        "power",
        "capacity",
        ["capacity_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_column("power", "picture_title")
    # ### end Alembic commands ###
