"""Add completion year

Revision ID: 6eb2d40a859e
Revises: 98b62ce09bef
Create Date: 2022-07-22 11:15:25.015390

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6eb2d40a859e"
down_revision = "98b62ce09bef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("proposed_completion_year", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "proposed_completion_year")
    # ### end Alembic commands ###
