"""Add power house floor

Revision ID: 70ce4bc948f2
Revises: 44574e6c7eda
Create Date: 2022-07-20 19:19:30.007832

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70ce4bc948f2"
down_revision = "44574e6c7eda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_data", sa.Column("power_house_floor", sa.Float(), nullable=True)
    )
    op.add_column("project_data", sa.Column("head_gross", sa.Float(), nullable=True))
    op.add_column("project_data", sa.Column("head_net", sa.Float(), nullable=True))
    op.add_column(
        "project_data", sa.Column("head_classification", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_data", "head_classification")
    op.drop_column("project_data", "head_net")
    op.drop_column("project_data", "head_gross")
    op.drop_column("project_data", "power_house_floor")
    # ### end Alembic commands ###
