"""Clean up project team

Revision ID: 74e60212e914
Revises: 566f0d09651f
Create Date: 2022-08-06 21:40:28.012829

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "74e60212e914"
down_revision = "566f0d09651f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_team",
        sa.Column(
            "has_manager", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.drop_column("project_team", "manager")
    op.drop_column("project_team", "manager_background")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_team",
        sa.Column("manager_background", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "project_team",
        sa.Column("manager", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("project_team", "has_manager")
    # ### end Alembic commands ###
