"""Fix project sectors

Revision ID: 77002e0c9436
Revises: c354a4ed6c3a
Create Date: 2022-05-18 18:40:34.328622

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "77002e0c9436"
down_revision = "c354a4ed6c3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "sector_id")
    op.add_column("project", sa.Column("sector_industry_id", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("sector_group_id", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("sector_division_id", sa.Text(), nullable=True))
    op.drop_column("project", "segment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("segment", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("project", "sector_division_id")
    op.drop_column("project", "sector_group_id")
    op.drop_column("project", "sector_industry_id")
    op.add_column(
        "power", sa.Column("sector_id", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
