"""Add other countries

Revision ID: 7c3672c3642e
Revises: 6eb2d40a859e
Create Date: 2022-07-22 11:22:40.668696

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7c3672c3642e"
down_revision = "6eb2d40a859e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("other_countries", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "other_countries")
    # ### end Alembic commands ###
