"""Add sponsor fields

Revision ID: 7df2395a0799
Revises: 3a5bc11e104a
Create Date: 2022-05-31 23:02:11.072146

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7df2395a0799"
down_revision = "3a5bc11e104a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_investment",
        "required_debt_amount",
        existing_type=sa.TEXT(),
        type_=sa.Float(),
        postgresql_using="NULL",
        existing_nullable=True,
    )
    op.add_column(
        "sponsor",
        sa.Column("sponsor_type_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column("sponsor", sa.Column("other_countries", sa.Text(), nullable=True))
    op.create_foreign_key(
        None,
        "sponsor",
        "sponsor_type",
        ["sponsor_type_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sponsor", type_="foreignkey")
    op.drop_column("sponsor", "other_countries")
    op.drop_column("sponsor", "sponsor_type_id")
    op.alter_column(
        "project_investment",
        "required_debt_amount",
        existing_type=sa.Float(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
