"""Add document section

Revision ID: 891f79839657
Revises: deb45b495956
Create Date: 2022-06-06 12:16:17.544928

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "891f79839657"
down_revision = "deb45b495956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_document", sa.Column("section", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_document", "section")
    # ### end Alembic commands ###
