"""Add strategy

Revision ID: 906edd47c0fd
Revises: 4f8cc396d56e
Create Date: 2022-06-21 21:09:00.725833

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "906edd47c0fd"
down_revision = "4f8cc396d56e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("capacity_mw", sa.Float(), nullable=True))
    op.add_column(
        "project_investment", sa.Column("investment_strategy", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_investment", "investment_strategy")
    op.drop_column("power", "capacity_mw")
    # ### end Alembic commands ###
