"""Add project debt description

Revision ID: 96cd5a1602da
Revises: 0f391f7d32df
Create Date: 2022-07-25 10:10:05.355486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96cd5a1602da'
down_revision = '0f391f7d32df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_investment', 'required_investment',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_investment', 'required_investment',
               existing_type=sa.Text(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
