"""Fix sponsors

Revision ID: 97d5fd1c96de
Revises: 5cae80dab9ec
Create Date: 2022-07-23 19:01:10.458582

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "97d5fd1c96de"
down_revision = "5cae80dab9ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE sponsor ALTER COLUMN other_countries TYPE text using other_countries::text"
    )
    op.execute(
        "ALTER TABLE sponsor ALTER COLUMN countries TYPE text[] using countries::text[]"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
