"""Add risk fields

Revision ID: 98b62ce09bef
Revises: c1fb2419ddb4
Create Date: 2022-07-21 20:56:35.163175

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "98b62ce09bef"
down_revision = "c1fb2419ddb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_management",
        sa.Column("guarantee_amount_mobilized", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_management", "guarantee_amount_mobilized")
    # ### end Alembic commands ###
