"""Add country & project partner listing

Revision ID: 9c9758aac45d
Revises: f159d39a763e
Create Date: 2022-08-06 10:01:07.683696

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9c9758aac45d"
down_revision = "f159d39a763e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("calling_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("country_pkey")),
    )
    op.drop_constraint("project_current_status_id_fkey", "project", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_current_status_id_fkey"),
        "project",
        "project_status",
        ["current_status_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.add_column(
        "project_partner", sa.Column("equity_partners_list", sa.Text(), nullable=True)
    )
    op.add_column(
        "project_partner", sa.Column("debt_partners_list", sa.Text(), nullable=True)
    )
    op.drop_constraint(
        "project_status_project_id_fkey", "project_status", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("project_status_project_id_fkey"),
        "project_status",
        "project",
        ["project_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_status_project_id_fkey"), "project_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "project_status_project_id_fkey",
        "project_status",
        "project",
        ["project_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.drop_column("project_partner", "debt_partners_list")
    op.drop_column("project_partner", "equity_partners_list")
    op.drop_constraint(
        op.f("project_current_status_id_fkey"), "project", type_="foreignkey"
    )
    op.create_foreign_key(
        "project_current_status_id_fkey",
        "project",
        "project_status",
        ["current_status_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.drop_table("country")
    # ### end Alembic commands ###
