"""Add featured

Revision ID: 9f070d6523fd
Revises: 394cfa521aad
Create Date: 2022-06-01 13:37:14.903742

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f070d6523fd"
down_revision = "394cfa521aad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("featured", sa.Integer(), server_default=sa.text("0"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "featured")
    # ### end Alembic commands ###
