"""Add stage

Revision ID: aeb01f9845c4
Revises: 5554d4bf0dd2
Create Date: 2022-06-21 20:26:17.923567

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aeb01f9845c4"
down_revision = "5554d4bf0dd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("completed_stage", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "completed_stage")
    # ### end Alembic commands ###
