"""Add brief description

Revision ID: b4796ba5e507
Revises: db76a45e22a3
Create Date: 2022-05-26 11:38:04.978604

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4796ba5e507"
down_revision = "db76a45e22a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "description")
    op.add_column("project", sa.Column("brief_description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "brief_description")
    op.add_column(
        "power", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
