"""Clean up name fields

Revision ID: b4d08a512418
Revises: e0d10d9b4b42
Create Date: 2022-05-26 20:16:32.801740

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4d08a512418"
down_revision = "e0d10d9b4b42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "full_name")
    op.drop_column("power", "short_name")
    op.add_column("project", sa.Column("short_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "short_name")
    op.add_column(
        "power", sa.Column("short_name", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "power", sa.Column("full_name", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
