"""Add users for auditing purposes

Revision ID: b5746f781323
Revises: 026db3b95da0
Create Date: 2022-07-28 11:20:09.652355

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b5746f781323"
down_revision = "026db3b95da0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("financial_performance", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("power", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("power_decision", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("power_impact", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("power_product", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("power_schedule", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("who", sa.Text(), nullable=True))
    op.drop_column("project", "status")
    op.add_column("project_contact", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_data", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_document", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_investment", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_legal", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_market", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_partner", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("project_team", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("risk_management", sa.Column("who", sa.Text(), nullable=True))
    op.add_column("sponsor", sa.Column("who", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsor", "who")
    op.drop_column("risk_management", "who")
    op.drop_column("project_team", "who")
    op.drop_column("project_partner", "who")
    op.drop_column("project_market", "who")
    op.drop_column("project_legal", "who")
    op.drop_column("project_investment", "who")
    op.drop_column("project_document", "who")
    op.drop_column("project_data", "who")
    op.drop_column("project_contact", "who")
    op.add_column(
        "project", sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("project", "who")
    op.drop_column("power_schedule", "who")
    op.drop_column("power_product", "who")
    op.drop_column("power_impact", "who")
    op.drop_column("power_decision", "who")
    op.drop_column("power", "who")
    op.drop_column("financial_performance", "who")
    # ### end Alembic commands ###
