"""Add data fields

Revision ID: b73406ca119c
Revises: 32d4f8b49a67
Create Date: 2022-05-31 23:49:20.004188

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b73406ca119c"
down_revision = "32d4f8b49a67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_data", sa.Column("weir_classification", sa.Text(), nullable=True)
    )
    op.add_column(
        "project_data", sa.Column("penstocks_length", sa.Float(), nullable=True)
    )
    op.add_column(
        "project_data", sa.Column("turbine_unit_size", sa.Float(), nullable=True)
    )
    op.add_column(
        "project_data", sa.Column("share_data_public", sa.Boolean(), nullable=True)
    )
    op.add_column("project_data", sa.Column("share_data", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_data", "share_data")
    op.drop_column("project_data", "share_data_public")
    op.drop_column("project_data", "turbine_unit_size")
    op.drop_column("project_data", "penstocks_length")
    op.drop_column("project_data", "weir_classification")
    # ### end Alembic commands ###
