"""Add stamp for images

Revision ID: b8ca18d810bc
Revises: 9f070d6523fd
Create Date: 2022-06-01 15:27:26.482665

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b8ca18d810bc"
down_revision = "9f070d6523fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("image_stamp", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "image_stamp")
    # ### end Alembic commands ###
