"""Add performance fields

Revision ID: c1fb2419ddb4
Revises: 5de0541ea584
Create Date: 2022-07-21 20:36:22.314977

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1fb2419ddb4"
down_revision = "5de0541ea584"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "financial_performance",
        sa.Column("power_sales_period", sa.Integer(), nullable=True),
    )
    op.add_column(
        "financial_performance",
        sa.Column("discounted_benefits", sa.Float(), nullable=True),
    )
    op.add_column(
        "financial_performance",
        sa.Column("discounted_costs", sa.Float(), nullable=True),
    )
    op.add_column(
        "financial_performance",
        sa.Column("average_annual_cashflow", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("financial_performance", "average_annual_cashflow")
    op.drop_column("financial_performance", "discounted_costs")
    op.drop_column("financial_performance", "discounted_benefits")
    op.drop_column("financial_performance", "power_sales_period")
    # ### end Alembic commands ###
