"""Add unique constraint

Revision ID: c6f0ff1407e1
Revises: 41b4a3c1487e
Create Date: 2022-05-20 07:30:25.110771

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c6f0ff1407e1"
down_revision = "41b4a3c1487e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "project_document_unique",
        "project_document",
        ["project_id", "document_type"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("project_document_unique", table_name="project_document")
    # ### end Alembic commands ###
