"""Add averages for product

Revision ID: d250e4056568
Revises: 09139eb84a48
Create Date: 2022-08-06 12:03:50.471274

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d250e4056568"
down_revision = "09139eb84a48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "power_product", sa.Column("average_price", sa.Float(), nullable=True)
    )
    op.add_column(
        "power_product", sa.Column("average_output", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power_product", "average_output")
    op.drop_column("power_product", "average_price")
    # ### end Alembic commands ###
