"""Add project description fields

Revision ID: d8cceca3dd8a
Revises: d73af65ba4e3
Create Date: 2022-05-19 17:52:54.512413

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d8cceca3dd8a"
down_revision = "d73af65ba4e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("objectives", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("location_area", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("milestones", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("impacts", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("award_criteria", sa.Text(), nullable=True))
    op.add_column(
        "project", sa.Column("comparative_advantage", sa.Text(), nullable=True)
    )
    op.add_column(
        "project", sa.Column("economic_contributions", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "economic_contributions")
    op.drop_column("project", "comparative_advantage")
    op.drop_column("project", "award_criteria")
    op.drop_column("project", "impacts")
    op.drop_column("project", "milestones")
    op.drop_column("project", "location_area")
    op.drop_column("project", "objectives")
    # ### end Alembic commands ###
