"""Add rev sources

Revision ID: d9e813aa0e3d
Revises: 22d9e24ef69a
Create Date: 2022-07-23 18:16:59.541415

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d9e813aa0e3d"
down_revision = "22d9e24ef69a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("other_revenue_sources", sa.Text(), nullable=True))
    op.execute(
        "ALTER TABLE power ALTER COLUMN other_revenue_sources TYPE text[] using other_revenue_sources::text[]"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "other_revenue_sources")
    # ### end Alembic commands ###
