"""Add project classification fields

Revision ID: e1444e3ae5e2
Revises: 62a3c25893a9
Create Date: 2022-07-26 13:38:01.384739

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e1444e3ae5e2"
down_revision = "62a3c25893a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "needs_investment",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "needs_advisory",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "needs_supply", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "needs_contractor",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "needs_contractor")
    op.drop_column("project", "needs_supply")
    op.drop_column("project", "needs_advisory")
    op.drop_column("project", "needs_investment")
    # ### end Alembic commands ###
