"""Add foreign keys

Revision ID: ed5eb43b2dab
Revises: 16d08ba7299c
Create Date: 2022-07-25 21:19:09.629910

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed5eb43b2dab"
down_revision = "16d08ba7299c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "power_capacity_id_fkey",
        "power",
        "capacity",
        ["capacity_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "project_data_turbine_capacity_id_fkey",
        "project_data",
        "capacity",
        ["turbine_capacity_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "project_data_turbine_capacity_id_fkey", "project_data", type_="foreignkey"
    )
    op.drop_constraint("power_capacity_id_fkey", "power", type_="foreignkey")
    # ### end Alembic commands ###
