"""Add project status

Revision ID: f159d39a763e
Revises: b5746f781323
Create Date: 2022-07-28 17:38:47.782608

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f159d39a763e"
down_revision = "b5746f781323"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_status",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("project_status_project_id_fkey"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_status_pkey")),
    )
    op.add_column(
        "project",
        sa.Column("current_status_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("project", sa.Column("verified_at", sa.DateTime(), nullable=True))
    op.create_foreign_key(
        op.f("project_current_status_id_fkey"),
        "project",
        "project_status",
        ["current_status_id"],
        ["id"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_current_status_id_fkey"), "project", type_="foreignkey"
    )
    op.drop_column("project", "verified_at")
    op.drop_column("project", "created_at")
    op.drop_column("project", "current_status_id")
    op.drop_table("project_status")
    # ### end Alembic commands ###
