"""Add capital fields

Revision ID: f375f2300e6f
Revises: 5059e9cd3773
Create Date: 2022-07-20 18:10:06.417885

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f375f2300e6f"
down_revision = "5059e9cd3773"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor", sa.Column("capital_required", sa.Float(), nullable=True))
    op.add_column("sponsor", sa.Column("capital_available", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsor", "capital_available")
    op.drop_column("sponsor", "capital_required")
    # ### end Alembic commands ###
