"""Add  product fields

Revision ID: f3d219950653
Revises: b73406ca119c
Create Date: 2022-06-01 01:01:45.300701

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f3d219950653"
down_revision = "b73406ca119c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "power_product", sa.Column("primary_customer", sa.Text(), nullable=True)
    )
    op.add_column(
        "power_product", sa.Column("other_customers", sa.Text(), nullable=True)
    )
    op.add_column(
        "power_product", sa.Column("other_customer_desc", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power_product", "other_customer_desc")
    op.drop_column("power_product", "other_customers")
    op.drop_column("power_product", "primary_customer")
    # ### end Alembic commands ###
