"""Add location

Revision ID: fdf2aa8f2630
Revises: b4796ba5e507
Create Date: 2022-05-26 12:05:04.990540

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fdf2aa8f2630"
down_revision = "b4796ba5e507"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("power", sa.Column("northings", sa.Text(), nullable=True))
    op.add_column("power", sa.Column("eastings", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("power", "eastings")
    op.drop_column("power", "northings")
    # ### end Alembic commands ###
